name: "Website update"

on:
  push:
    branches:
      - master

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate sphinx website
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip3 -q install sphinx-material sphinxcontrib-bibtex"
        docs-folder: .
    - name: Fix permissions and add CNAME file
      run: |
        sudo chown $USER _build -R
        echo "www.rbnicsproject.org" > _build/html/CNAME
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        user_name: 'GitHub Actions'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'
