name: "Website update"

on:
  push:
    branches:
      - "**"
      - "!gh-pages"
      - "!open-in-colab-rbnicsx"
  workflow_dispatch:

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate sphinx website
      uses: ax3l/sphinx-action@newer-sphinx
      with:
        pre-build-command: "pip3 -q install sphinx-material 'sphinxcontrib-bibtex<2.0.0'"
        docs-folder: .
    - name: Fix permissions and add CNAME file
      run: |
        sudo chown $USER _build -R
        echo "www.rbnicsproject.org" > _build/html/CNAME
    - name: Deploy to GitHub pages
      if: github.repository == 'RBniCS/rbnicsproject.org' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        user_name: 'GitHub Actions'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Deploy to GitHub artifacts
      if: github.repository == 'RBniCS/rbnicsproject.org' && github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: _build/html
        retention-days: 1
