name: "Website update"

on:
  push:
    branches:
      - master

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate sphinx website
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip3 -q install sphinx-material"
        docs-folder: .
    - name: Fix email addresses
      run: find _build/html -type f -exec sed -i 's/%40/@/g' {} +
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html

