name: "Website update"

on:
  push:
    branches:
      - master

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate sphinx website
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip3 -q install sphinx-material sphinxcontrib-bibtex"
        docs-folder: .
    - name: Fix permissions, email addresses and CNAME file
      run: |
        sudo chown $USER _build -R
        find _build/html -type f -exec sed -i 's/%40/@/g' {} +
        echo "www.rbnicsproject.org" > _build/html/CNAME
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
